# Generated by Django 5.2.6 on 2025-09-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
