# Generated by Django 5.1.1 on 2025-09-25 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст для поиска')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Поисковый индекс',
                'verbose_name_plural': 'Поисковые индексы',
            },
        ),
    ]
