<<<<<<< HEAD
# Generated by Django 5.1.1 on 2025-09-19 07:47

import django.db.models.deletion
=======
# Generated by Django 5.2.6 on 2025-09-21 13:49

>>>>>>> feature/search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('recipes', '0001_initial'),
=======
>>>>>>> feature/search
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст для поиска')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Поисковый индекс',
                'verbose_name_plural': 'Поисковые индексы',
            },
=======
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
            ],
>>>>>>> feature/search
        ),
    ]
