# Generated by Django 5.1.1 on 2025-09-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchIndex',
        ),
    ]
